name = "ded-blog-upload"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "upload.derekethandavis.com", custom_domain = true }
]

[[r2_buckets]]
binding = "AUDIO"
bucket_name = "ded-blog-audio"

[ai]
binding = "AI"

[vars]
SANITY_PROJECT_ID = "3onlytdh"
SANITY_DATASET = "production"
CLOUDFLARE_ACCOUNT_ID = "d810128e93e1fd0f94b4948fd3edadfb"
